# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 687f24842dd69d665b4a0e58be127c2a954415de4f8bf6e6547aaab6932974c1150ada2b039730917d9506fef1e3ac81f22d969cc667b5593cfc2029c077c154

test:
  secret_key_base: e798232b202fa0f6dd43561a412596ede6c3b69e6a4a337b0a8a7bc5e5454f1071dc54ece844c4eb925a3187c1e30a6b6d10d37dc8eeb3602255eea862c46d21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
